name: onesignal_flutter
description: OneSignal is a free push notification service for mobile apps. This plugin makes it easy to integrate your flutter app with OneSignal
version: 2.6.1
homepage: https://github.com/OneSignal/OneSignal-Flutter-SDK

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.onesignal.flutter
        pluginClass: OneSignalPlugin
      ios:
        pluginClass: OneSignalPlugin
